### PR TITLE
Render fixes

### PR DESCRIPTION
**Pull request by araffin**
- allow to pass a render mode for the v0 (no RGB) env
- added rgb array rendering for non-rgb env
- fixed fps when showing the env
- fixed the windows showing "window not responding when rendering"

### CODE REVIEW

**Comment by sapphire008** [comment]
This is a much needed feature. It will help "export" the output as images.

**Comment by Sookeyy-12** [comment]
@markub3327 please merge this pr, its a handy feature

**Comment by markub3327** [comment]
@araffin Thanks for this amazing PR.

Feel free to contributing.

**Comment by araffin** [comment]
Your welcome =)
fyi, it was used recently for a dqn tutorial at the rl summer school: https://github.com/araffin/rlss23-dqn-tutorial

**Pull request merged**
